/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "PWM.h"
#include "UART.h"
#include "Motor_aliases.h"
#include "Motor.h"
#include "Timer.h"
#include "LCD.h"
#include "Clock_1.h"
#include "HE_Interrupt.h"
#include "HallEffect_aliases.h"
#include "HallEffect.h"
#include "Clock_2.h"
#include "CamOut_aliases.h"
#include "CamOut.h"
#include "Comp.h"
#include "Black.h"
#include "OddEven_aliases.h"
#include "OddEven.h"
#include "StartFrame.h"
#include "HSync_aliases.h"
#include "HSync.h"
#include "VDAC8_1.h"
#include "VideoTimer.h"
#include "Counter.h"
#include "Pin_1_aliases.h"
#include "Pin_1.h"
#include "Pin_2_aliases.h"
#include "Pin_2.h"
#include "UART_IntClock.h"
#include "LCD_LCDPort_aliases.h"
#include "LCD_LCDPort.h"
#include "cy_em_eeprom.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

